[server]
headless = true
port = $PORT
enableCORS = false
maxUploadSize = 200

[theme]
primaryColor = "#B1510F"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[browser]
gatherUsageStats = false
